### ISSUE TITLE
Error downloading public data - is it possible to use .csv file instead?

### ISSUE THREAD

**Issue by madi** [usnistgov/SDNist#7]
Hi,

running 

>>> import sdnist
>>> dataset, schema = sdnist.census()

I get:

data/census/final/IL_OH_10Y_PUMS.json does not exist.
Downloading https://data.nist.gov/od/ds/mds2-2515/IL_OH_10Y_PUMS.json ...
data/census/final/IL_OH_10Y_PUMS.parquet does not exist.
Downloading https://data.nist.gov/od/ds/mds2-2515/IL_OH_10Y_PUMS.parquet ...
Traceback (most recent call last):
  File "/home/madi/.local/lib/python3.8/site-packages/sdnist/load.py", line 15, in check_exists
    urllib.request.urlretrieve(
  File "/usr/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1358, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/madi/.local/lib/python3.8/site-packages/sdnist/load.py", line 111, in load_dataset
    check_exists(dataset_name, download)
  File "/home/madi/.local/lib/python3.8/site-packages/sdnist/load.py", line 21, in check_exists
    raise RuntimeError(f"Unable to download {name}. \n You can attempt to download manually from https://data.nist.gov/od/ds/mds2-2515 and install to {name}")
RuntimeError: Unable to download data/census/final/IL_OH_10Y_PUMS.parquet. 
 You can attempt to download manually from https://data.nist.gov/od/ds/mds2-2515 and install to data/census/final/IL_OH_10Y_PUMS.parquet

I understand that the server where the public data sits is not available at the moment. I do have the public dataset in my local computer, in csv format. What I want to understand is how can I use the csv file that I have to generate this .parquet file or, better, if I can directly feed the csv to the synthesizer. Thanks

**Comment by garyhowarth** [comment]
Thank you for raising the issue. Here are two possible remedies: 
- Today, we have published [SNist-1.2.0 as a Release](https://github.com/usnistgov/SDNist/releases/tag/v1.2.0) containing all of the data tables in both parquet/json and csv. So these should be available even if the NIST servers are unresponsive.
- To convert from parquet to csv and back in Python, use the Pandas library: 

```
Python 3.8.3
>>> import pandas as pd
>>> df = pd.read_csv('./data.csv')
>>> df.to_parquet('./data.parquet')
>>> df2 = pd.read_parquet('./data.parquet')
>>> df2.to_csv('./same_data.csv')
```

**Comment by madi** [comment]
Thank you @garyhowarth for the timely response!

**Comment by madi** [comment]
Is there an example usage for feeding the path of the dataset to the tool?

**Comment by garyhowarth** [comment]
We have reconfigured the NIST servers to play nice with python requests. This remedies approximately 90% of download problems.
